[package]
name = "antoine/collectsell"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4.0.0"
Networker = "leifstout/networker@0.3.1"
React = "jsdotlua/react@17.2.1"
ReactRoblox = "jsdotlua/react-roblox@17.2.1"

[server-dependencies]
ProfileService = "firebird702/profileservice@1.1.0"
